using SoundCore.UI;

namespace SoundCore;

internal static class Program
{
    /// <summary>
    /// Main entry point of the application.
    /// </summary>
    [STAThread]
    static void Main()
    {
        // Enables visual styles, high-quality text rendering and the
        // application theme (auto-generated by the WinForms SDK).
        ApplicationConfiguration.Initialize();

        // Ventana extra: reproductor DJ "G" (se abre junto con el programa).
        var main = new MainForm();
        var player = new PlayerForm();
        main.Shown += (_, _) => player.Show();

        // La ventana de red NO se abre aquí: se abre desde el botón
        // "Conexión de Red" del formulario principal.

        Application.Run(main);
    }
}
